#!/bin/bash

[ "$#" -lt 2 ] && echo "Usage: ./with-hosts <hosts_file> <cmd> [args]" && exit 1

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
export HOSTS_FILE=$(readlink -f "$1")
shift
export LD_PRELOAD="$SCRIPT_DIR/libhostspriv.so"
exec $@
