#!/bin/bash -e

if [ "$#" -lt 1 ]; then
   echo "Usage: ./with-hosts <hosts_file> [cmd [args...]]" >&2
   exit 1
fi

export HOSTS_FILE=$(readlink -f "$1")
shift

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
LIB="$SCRIPT_DIR/libhostspriv.so"
if [ ! -f "$LIB" ]; then
	make -C "$SCRIPT_DIR"
fi
export LD_PRELOAD="$LIB:$LD_PRELOAD"

if [ "$#" -eq 0 ]; then
	exec $SHELL
else
	exec $@
fi
