#!/bin/bash

if [ "$#" -lt 1 ]; then
   echo "Usage: ./with-hosts <hosts_file> [cmd [args...]]" >&2
   exit 1
fi

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
export HOSTS_FILE=$(readlink -f "$1")
shift
export LD_PRELOAD="$SCRIPT_DIR/libhostspriv.so"
if [ "$#" -eq 0 ]; then
	exec $SHELL
else
	exec $@
fi
